domains:
  machine_learning:
    - tensorflow
    - keras
    - pytorch
    - scikit-learn
    - taichi
    - librosa
  web:
    - django
    - streamlit
    - sanic
    - fastapi
    - flask
    - uvicorn
    - tornado
    - beautifulsoup
    - gunicorn
  data_science:
    - scipy
    - nltk
    - matplotlib
    - pandas
    - geopandas
    - seaborn
  infrastructure:
    - airflow
    - numpy
    - SeleniumBase
    - dask
    - celery
    - black
    - pytest
    - cryptography
    - requests
    - tqdm
    - ansible
    - glances
    - mitmproxy
  embedded:
    - paho.mqtt.python
    - gpiozero
    - rclpy
