repos:
- synth
smells:
  synth:
    long-lambda-expr:
    - 18ff6862
    - '70892924'
    - 9acefbaf
    - c7496f4f
    long-message-chain:
    - 886a20f4
    - 9c65bec9
    - b0bca795
    - b434f086
    no-self-use:
    - 34a8d49c
    - dd5452c6
    string-concat-loop:
    - 17abe9ba
    - 7196cd51
    - 7870bf53
    - a1897552
    too-many-arguments:
    - 0a31c3d7
    - 0f94663e
    - 63e31e14
    - ad943db7
    use-a-generator:
    - 202a4bc1
    - 470013c7
    - 70a52d09
    - fae4b02f
